[package]
name = "polyhedron-ops"
version = "0.1.3"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
keywords = ["3d", "creative", "geometry", "graphics", "rendering"]
categories = ["graphics", "mathematics", "multimedia", "rendering"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Conway/Hart Polyhedron Operations"
readme = "README.md"
repository = "https://github.com/virtualritz/polyhedron-ops/"
documentation = "https://docs.rs/polyhedron-ops/"

[features]
default = []

[dependencies]
clamped = "1.0.0"
ultraviolet = "0.7.5"
itertools = "0.9.0"
rayon = "1.5.0"
# Add code to render polyhedra with NSI.
nsi = { version = "0.5.6", optional = true }

[dev-dependencies]
dirs = "3.0.1"
nalgebra = "0.23.1"
kiss3d = "0.28.0"
slice_as_array = "1.1.0"

[profile.release]
lto = "on"
opt-level = 3
codegen-units = 1

[profile.dev.package.'*']
opt-level = 3

[[example]]
path = "examples/playground/playground.rs"
name = "playground"


[package.metadata.docs.rs]
features = [ "nsi" ]
