[package]
name = "polyhedron-ops"
version = "0.2.2"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
keywords = ["3d", "creative", "geometry", "graphics", "rendering"]
categories = ["graphics", "mathematics", "multimedia", "rendering"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Conway/Hart Polyhedron Operations"
readme = "README.md"
repository = "https://github.com/virtualritz/polyhedron-ops/"
documentation = "https://docs.rs/polyhedron-ops/"

[features]
default = []
# Add support for writing a mesh out as a Wavefront OBJ.
obj = []

[dependencies]
bytemuck = "1.4.1"
clamped = "1.0.0"
itertools = "0.10.0"
num-traits = "0.2.14"
rayon = "1.5.0"
ultraviolet = { version = "0.7.5", features = [ "f64" ] }
# Optional deps.
# Add support to render polyhedra with NSI.
nsi = { version = "0.6.0", optional = true }
# Add support to convert a Polyhedron into a bevy Mesh.
bevy = { version = "0.4.0", optional = true }

[dev-dependencies]
dirs = "3.0.1"
nalgebra = "0.24.0"
kiss3d = { git = "https://github.com/sebcrozet/kiss3d.git" }
slice_as_array = "1.1.0"
bevy-orbit-controls = "1.0.1"

[profile.release]
lto = "on"
opt-level = 3
codegen-units = 1

[profile.dev.package.'*']
opt-level = 3

[[example]]
path = "examples/playground/playground.rs"
name = "playground"
required-features = [ "obj" ]

[[example]]
path = "examples/bevy/bevy.rs"
name = "bevy"
required-features = [ "bevy" ]

[package.metadata.docs.rs]
features = [ "nsi", "obj" ]
